# Generated by Django 5.1.3 on 2024-12-02 14:43

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='signature',
            field=models.ImageField(blank=True, help_text='Signature image (max 500KB)', null=True, upload_to=users.models.signature_upload_path, validators=[users.models.validate_file_size]),
        ),
    ]
